# Generated by Django 3.0.7 on 2023-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230726_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=255)),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
    ]
